//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITMSEntities1 : DbContext
    {
        public ITMSEntities1()
            : base("name=ITMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_inventory> tbl_inventory { get; set; }
        public virtual DbSet<tbl_report> tbl_report { get; set; }
        public virtual DbSet<tbl_ticket> tbl_ticket { get; set; }
    }
}
