//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_report
    {
        public int IDrep { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IDUser { get; set; }
        public string rep_desc { get; set; }
        public Nullable<System.DateTime> submittedDate { get; set; }
    }
}
