//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ticket
    {
        public int IDticket { get; set; }
        public string task_type { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<System.DateTime> TicketDate { get; set; }
        public Nullable<int> IDrep { get; set; }
        public Nullable<int> IDtechnician { get; set; }
        public string ticketStatus { get; set; }
    }
}
