//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inventory
    {
        public int IDinv { get; set; }
        public string invName { get; set; }
        public Nullable<int> invQty { get; set; }
    }
}
